"""Shared state helpers."""

from __future__ import annotations

from typing import Any


REQUIRED_STATE_KEYS = (
    "task",
    "active_task",
    "routing",
    "tool_selection",
    "strategy",
    "executed_flow",
    "plan",
    "current_step",
    "build",
    "artifacts",
    "policy",
    "testing",
    "critique",
    "debugging",
    "analysis",
    "objections",
    "research",
    "next_step",
    "session_strategy",
    "subtasks",
    "current_subtask",
    "completed_subtasks",
    "task_board",
    "priorities",
    "task_guidance",
    "current_round",
    "session_history",
    "final_result",
    "capability_report",
    "memory",
    "recovery_plan",
    "escalation",
    "export",
    "history",
)


def create_state(task: str) -> dict[str, Any]:
    """Create the shared state used by the orchestrator and agents."""
    return {
        "task": task,
        "active_task": task,
        "routing": {},
        "tool_selection": {},
        "strategy": {},
        "executed_flow": [],
        "plan": {"steps": [], "summary": ""},
        "current_step": None,
        "build": {},
        "artifacts": {"items": []},
        "policy": {},
        "testing": {},
        "critique": {},
        "debugging": {},
        "analysis": {},
        "objections": {},
        "research": {},
        "next_step": {},
        "session_strategy": {},
        "subtasks": [],
        "current_subtask": "",
        "completed_subtasks": [],
        "task_board": {"items": []},
        "priorities": {},
        "task_guidance": "",
        "current_round": 1,
        "session_history": [],
        "final_result": {},
        "capability_report": {},
        "memory": {},
        "recovery_plan": {},
        "escalation": {},
        "export": {},
        "history": [],
    }
